# Generated by Django 3.2.5 on 2021-07-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
